#!/bin/bash

export $MAC
export $TYPE
export $SSID

[[ "$(uci get reporting.settings.tracking)" == "1" ]] && {
	[[ "$TYPE" == "0" ]] && {
	    echo "$(date): Probe request from $MAC for SSID '$SSID'" >> /tmp/tracking.report
	} || {
	    echo "$(date): Association from $MAC to SSID '$SSID'" >> /tmp/tracking.report
	}
}

/etc/pineapple/tracking_script_user
